### ISSUE TITLE
Problem with range matching.

### ISSUE THREAD

**Issue by gmosx** [Hexagon/croner-rust#11]
Hi!

First of all, thank you for this useful crate. I would like to report an issue:

The cron expression `0 0 15-21 3 5` should match a Friday in March that's between the days 15-21.

In other words it should match `15-21` AND `5`, i.e. "3-15".

Instead it seems to match `15-21` _OR_ `5`, i.e.  "3-1" "3-8" "3-15" "3-16" "3-17" "3-18" "3-19" "3-20" "3-21" "3-22" "3-29".

**Comment by Hexagon** [comment]
Hello! That's expected behavior of cron, but croner has an option for using OR instead of AND - https://github.com/Hexagon/croner-rust?tab=readme-ov-file#3-with_dom_and_dow . Does that work for you?

**Comment by Hexagon** [comment]
Background (from developing the javascript version of croner): https://github.com/Hexagon/croner/issues/53

**Comment by gmosx** [comment]
Interesting, I will check this out!

**Comment by gmosx** [comment]
Shouldn't `.with_dom_and_dow()` be the default?

**Comment by gmosx** [comment]
Closing this issue as my problem is resolved.

But, a thought: shouldn't `.with_dom_and_dow()` be the default?

**Comment by gmosx** [comment]
Closing this issue as my problem is resolved.

But, a thought: shouldn't `.with_dom_and_dow()` be the default?

**Comment by Hexagon** [comment]
Great! 

OR is the default in most cron implementations, including the POSIX crontab specification

> As an example of specifying the two types of days:
> 
> 0 0 1,15 * 1
> 
> would run a command on the first and fifteenth of each month, as well as on every Monday. To specify days by only one field, the other field should be set to '*'; for example:

- https://pubs.opengroup.org/onlinepubs/9799919799/utilities/crontab.html
